#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-PDO_SQLANYWHERE
Version  : 0.1.4
Release  : 1
URL      : https://pecl.php.net//get/PDO_SQLANYWHERE-0.1.4.tgz
Source0  : https://pecl.php.net//get/PDO_SQLANYWHERE-0.1.4.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: php-PDO_SQLANYWHERE-lib = %{version}-%{release}
BuildRequires : buildreq-php

%description
No detailed description available

%package lib
Summary: lib components for the php-PDO_SQLANYWHERE package.
Group: Libraries

%description lib
lib components for the php-PDO_SQLANYWHERE package.


%prep
%setup -q -n PDO_SQLANYWHERE-0.1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20180731/pdo_sqlanywhere.so
